Musik/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands, only: [:index, :create, :new, :show, :update, :destroy]
end

Musik/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Musik/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true

    def index
        @band = Band.all
        render :index
    end

    def create
        @band = Band.find_by(band_params)

        if @band.save

        else
            flash.now[:errors] = @band.errors.full_messages
        end
    end

    def new
        @band = Band.new
        render :new
    end

    def show
        render :show
    end

end

Musik/app/models/user.rb
class User < ApplicationRecord
    validates :email, :password_digest, :session_token, presence: true
    validates :password, length: { minimum: 6, allow_nil: true }

    attr_reader :password

    after_initialize :ensure_session_token


    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        user && user.is_password?(password) ? user : nil
    end

    # def self.generate_session_token
    #     SecureRandom::urlsafe_base64
    # end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end
end

Musik/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  # def ensure_logged_in
  #   redirect_to new_session_url
  # end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

end

Musik/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
        render :new
    end
    
    def create
        @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if @user
            login!(@user)
            redirect_to user_url(@user.id)
        else
            flash.now[:errors] = ['Invalid user']
            @user = User.new
            render :new
        end
    end

    def destroy
        @user = User.find_by(session_token: session[:session_token])
        @user.reset_session_token!
        session[:session_token] = nil
        redirect_to new_session_url
    end
end

Musik/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to user_url(@user.id)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        render :show
        # @user = User.find_by(id: params[:id])

        # if @user
        #     render :show
        # else
        #     redirect_to user_url
        # end
    end

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

Musik/app/helpers/application_helper.rb
module ApplicationHelper
end

Musik/app/helpers/sessions_helper.rb
module SessionsHelper
end

Musik/app/helpers/users_helper.rb
module UsersHelper
end

Musik/app/views/bands/index.html.erb
<H1>Bands That Make Her Dance</H1>

<% @band.each do |band| %>

    <ul>
        <li><a href="<%= band_url(band) %>"><p><%= band.name %></p></a></li>
    </ul>

<% end %>

Musik/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musik</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%  if logged_in? %>

    <%= current_user.email %>
    <form action="<%= session_url %>" method= 'POST'>
     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="sign-out">    
    </form>
    <% else %>
      <a href=" <%= new_user_url %>">Sign-up</a>
      <a href=" <%= new_session_url  %>">Sign-in</a>
    <% end %>
    
    <%= yield %>
  </body>
</html>

Musik/app/views/users/new.html.erb
<H1>Let's play Musik</H1>

<form action="<%= users_url %>" method="POST">
  
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
  
    <label>
      Email
      <input type="text" name="user[email]" value="<%= @user.email %>" />
    </label>

  <br>
    
    <label>
      Password
      <input type="password" name="user[password]" value="" />
    </label>

  <br>
  
  <input type="submit" value="Assimilate" />

</form>

Musik/app/views/users/show.html.erb
    <h1>welcome to the show</h1>